-- Supabase tables for NuroAgro mirrored history.
-- Run this in the Supabase SQL editor before enabling remote writes.

create table if not exists public.sensor_readings (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    device_id text not null,
    temperature double precision,
    humidity double precision,
    soil_moisture double precision,
    mq2_reading double precision,
    mq5_reading double precision,
    mq7_reading double precision,
    mq135_reading double precision,
    sound_level double precision,
    light_intensity double precision,
    rain_level double precision,
    water_level double precision,
    motion_detected boolean,
    pump_status boolean,
    light_status boolean,
    timestamp timestamptz not null default now()
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    local_id bigint,
    username text,
    email text,
    full_name text,
    phone text,
    profile_notes text,
    farm_name text,
    farm_location_lat double precision,
    farm_location_lon double precision,
    farm_size double precision,
    farm_area_suitability double precision,
    geolocation_analyzed boolean default false,
    plant_type text,
    approval_status text default 'pending',
    profile_details jsonb,
    planting_date timestamptz,
    created_at timestamptz,
    updated_at timestamptz
);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    project_name text not null,
    farming_mode text,
    water_system text,
    land_area double precision,
    vertical_stories integer check (vertical_stories between 1 and 4),
    latitude double precision,
    longitude double precision,
    weather_snapshot jsonb,
    ai_suitability jsonb,
    recommended_plants jsonb,
    recommended_fish jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.devices (
    id bigint generated by default as identity primary key,
    local_id bigint,
    device_id text not null,
    user_id bigint not null,
    device_name text,
    device_type text,
    is_active boolean default true,
    last_heartbeat timestamptz,
    firmware_version text,
    device_location_lat double precision,
    device_location_lon double precision,
    created_at timestamptz,
    updated_at timestamptz
);

create table if not exists public.device_statuses (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    device_id text not null,
    pump_on boolean default false,
    light_on boolean default false,
    pump_b_on boolean default false,
    uv_light_level double precision,
    last_watering timestamptz,
    next_scheduled_watering timestamptz,
    auto_watering_enabled boolean default true,
    moisture_threshold double precision,
    last_command text,
    last_command_time timestamptz,
    updated_at timestamptz
);

create table if not exists public.recommendations (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    recommendation_type text,
    suitable_plants jsonb,
    plant_score double precision,
    expected_yield double precision,
    cost_estimate double precision,
    growing_period integer,
    reason text,
    based_on_factors jsonb,
    recommended_month integer,
    time_of_analysis timestamptz not null default now(),
    is_active boolean default true,
    user_accepted boolean
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    notification_type text,
    title text,
    message text,
    triggered_by text,
    related_id bigint,
    is_read boolean default false,
    is_dismissed boolean default false,
    created_at timestamptz not null default now(),
    read_at timestamptz
);

create table if not exists public.disease_detections (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    device_id text,
    image_path text,
    image_url text,
    is_from_camera boolean default false,
    detections jsonb,
    primary_disease text,
    disease_confidence double precision,
    recommendations jsonb,
    severity_level text,
    timestamp timestamptz not null default now()
);

create table if not exists public.weather_records (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    device_id text,
    project_id bigint,
    source text default 'predicted',
    horizon_minutes integer default 30,
    max_temperature double precision,
    min_temperature double precision,
    apparent_temperature double precision,
    humidity double precision,
    pressure double precision,
    rainfall double precision,
    confidence double precision,
    model_status text,
    raw_payload jsonb,
    agent_summary text,
    recommended_plants jsonb,
    forecast_for timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.weather_training_runs (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    device_id text,
    samples_count integer default 0,
    accuracy_score double precision,
    mean_absolute_error double precision,
    status text default 'queued',
    model_version text,
    details jsonb,
    started_at timestamptz,
    completed_at timestamptz
);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    sender_role text default 'user',
    message text not null,
    is_read boolean default false,
    created_at timestamptz not null default now()
);

create table if not exists public.forum_posts (
    id bigint generated by default as identity primary key,
    local_id bigint,
    user_id bigint not null,
    title text not null,
    category text default 'general',
    content text not null,
    plant_type text,
    is_resolved boolean default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

create table if not exists public.forum_replies (
    id bigint generated by default as identity primary key,
    local_id bigint,
    post_id bigint not null,
    user_id bigint not null,
    content text not null,
    created_at timestamptz not null default now()
);
create table if not exists public.admin_events (
    id bigint generated by default as identity primary key,
    admin_id text,
    action text not null,
    target_user_id bigint,
    details jsonb,
    created_at timestamptz not null default now()
);

-- Idempotent migrations for older NuroAgro Supabase projects.
alter table public.users add column if not exists local_id bigint;
alter table public.users add column if not exists approval_status text default 'pending';
alter table public.users add column if not exists full_name text;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists profile_notes text;

alter table public.sensor_readings add column if not exists local_id bigint;
alter table public.sensor_readings add column if not exists rain_level double precision;
alter table public.sensor_readings add column if not exists water_level double precision;
alter table public.sensor_readings add column if not exists motion_detected boolean;

alter table public.projects add column if not exists local_id bigint;
alter table public.devices add column if not exists local_id bigint;

alter table public.device_statuses add column if not exists local_id bigint;
alter table public.device_statuses add column if not exists pump_b_on boolean default false;
alter table public.device_statuses add column if not exists uv_light_level double precision;

alter table public.recommendations add column if not exists local_id bigint;
alter table public.notifications add column if not exists local_id bigint;
alter table public.disease_detections add column if not exists local_id bigint;
alter table public.weather_records add column if not exists local_id bigint;
alter table public.weather_records add column if not exists user_id bigint;
alter table public.weather_records add column if not exists device_id text;
alter table public.weather_records add column if not exists project_id bigint;
alter table public.weather_records add column if not exists source text default 'predicted';
alter table public.weather_records add column if not exists horizon_minutes integer default 30;
alter table public.weather_records add column if not exists max_temperature double precision;
alter table public.weather_records add column if not exists min_temperature double precision;
alter table public.weather_records add column if not exists apparent_temperature double precision;
alter table public.weather_records add column if not exists humidity double precision;
alter table public.weather_records add column if not exists pressure double precision;
alter table public.weather_records add column if not exists rainfall double precision;
alter table public.weather_records add column if not exists confidence double precision;
alter table public.weather_records add column if not exists model_status text;
alter table public.weather_records add column if not exists raw_payload jsonb;
alter table public.weather_records add column if not exists agent_summary text;
alter table public.weather_records add column if not exists recommended_plants jsonb;
alter table public.weather_records add column if not exists forecast_for timestamptz;
alter table public.weather_records add column if not exists created_at timestamptz default now();

alter table public.weather_training_runs add column if not exists local_id bigint;
alter table public.weather_training_runs add column if not exists user_id bigint;
alter table public.weather_training_runs add column if not exists device_id text;
alter table public.weather_training_runs add column if not exists samples_count integer default 0;
alter table public.weather_training_runs add column if not exists accuracy_score double precision;
alter table public.weather_training_runs add column if not exists mean_absolute_error double precision;
alter table public.weather_training_runs add column if not exists status text default 'queued';
alter table public.weather_training_runs add column if not exists model_version text;
alter table public.weather_training_runs add column if not exists details jsonb;
alter table public.weather_training_runs add column if not exists started_at timestamptz;
alter table public.weather_training_runs add column if not exists completed_at timestamptz;
alter table public.chat_messages add column if not exists local_id bigint;
alter table public.chat_messages add column if not exists user_id bigint;
alter table public.chat_messages add column if not exists sender_role text default 'user';
alter table public.chat_messages add column if not exists message text;
alter table public.chat_messages add column if not exists is_read boolean default false;
alter table public.chat_messages add column if not exists created_at timestamptz default now();

alter table public.forum_posts add column if not exists local_id bigint;
alter table public.forum_posts add column if not exists user_id bigint;
alter table public.forum_posts add column if not exists title text;
alter table public.forum_posts add column if not exists category text default 'general';
alter table public.forum_posts add column if not exists content text;
alter table public.forum_posts add column if not exists plant_type text;
alter table public.forum_posts add column if not exists is_resolved boolean default false;
alter table public.forum_posts add column if not exists created_at timestamptz default now();
alter table public.forum_posts add column if not exists updated_at timestamptz;

alter table public.forum_replies add column if not exists local_id bigint;
alter table public.forum_replies add column if not exists post_id bigint;
alter table public.forum_replies add column if not exists user_id bigint;
alter table public.forum_replies add column if not exists content text;
alter table public.forum_replies add column if not exists created_at timestamptz default now();
alter table public.admin_events add column if not exists local_id bigint;

-- The Flask backend upserts mirrored rows by local_id to avoid duplicate cloud rows.
create unique index if not exists users_local_id_key on public.users(local_id);
create unique index if not exists sensor_readings_local_id_key on public.sensor_readings(local_id);
create unique index if not exists projects_local_id_key on public.projects(local_id);
create unique index if not exists devices_local_id_key on public.devices(local_id);
create unique index if not exists device_statuses_local_id_key on public.device_statuses(local_id);
create unique index if not exists recommendations_local_id_key on public.recommendations(local_id);
create unique index if not exists notifications_local_id_key on public.notifications(local_id);
create unique index if not exists disease_detections_local_id_key on public.disease_detections(local_id);
create unique index if not exists weather_records_local_id_key on public.weather_records(local_id);
create unique index if not exists weather_training_runs_local_id_key on public.weather_training_runs(local_id);
create unique index if not exists chat_messages_local_id_key on public.chat_messages(local_id);
create unique index if not exists forum_posts_local_id_key on public.forum_posts(local_id);
create unique index if not exists forum_replies_local_id_key on public.forum_replies(local_id);
create unique index if not exists admin_events_local_id_key on public.admin_events(local_id);

-- REST grants for the publishable-key backend bridge.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- If RLS is enabled in Supabase, these policies allow the Flask bridge to mirror data.
-- For production, prefer a service-role key on the backend and replace these broad policies
-- with user-scoped policies.
drop policy if exists nuroagro_bridge_all on public.users;
create policy nuroagro_bridge_all on public.users for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.sensor_readings;
create policy nuroagro_bridge_all on public.sensor_readings for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.projects;
create policy nuroagro_bridge_all on public.projects for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.devices;
create policy nuroagro_bridge_all on public.devices for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.device_statuses;
create policy nuroagro_bridge_all on public.device_statuses for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.recommendations;
create policy nuroagro_bridge_all on public.recommendations for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.notifications;
create policy nuroagro_bridge_all on public.notifications for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.disease_detections;
create policy nuroagro_bridge_all on public.disease_detections for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.weather_records;
create policy nuroagro_bridge_all on public.weather_records for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.weather_training_runs;
create policy nuroagro_bridge_all on public.weather_training_runs for all to anon, authenticated using (true) with check (true);


drop policy if exists nuroagro_bridge_all on public.chat_messages;
create policy nuroagro_bridge_all on public.chat_messages for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.forum_posts;
create policy nuroagro_bridge_all on public.forum_posts for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.forum_replies;
create policy nuroagro_bridge_all on public.forum_replies for all to anon, authenticated using (true) with check (true);

drop policy if exists nuroagro_bridge_all on public.admin_events;
create policy nuroagro_bridge_all on public.admin_events for all to anon, authenticated using (true) with check (true);

